### PR TITLE
Enable win10 arm builds

### PR DESCRIPTION
**Pull request by aaomidi**
This enables sqltoolsservice to be published for arm machines as well.

### CODE REVIEW

**Comment by anthonydresser** [comment]
do we actually have a use case for this?

**Comment by aaomidi** [comment]
It's been a feature request here: https://github.com/microsoft/azuredatastudio/issues/1774

I just thought I'd start on the sqltoolsservice side since the ads side shouldn't be terribly difficult considering I've seen repos like this do it: https://github.com/stevedesmond-ca/vscode-arm

**Comment by aaomidi** [comment]
The reason I opened the PR is also to see what the team generally thinks about just having these built & published and then used later on.

**Comment by Charles-Gagnon** [comment]
Yeah I remembered the people asking about that right after I said that. Fine with experimentation - do you have any idea how complicated this would be to add on the ADS side?

**Comment by aaomidi** [comment]
I don't suspect it being that difficult, we have some node modules that might give us some problems

(Looking at you Kerberos)

But I think just getting a test build manually built out by hand and validating it shouldn't be terribly difficult)

**Comment by aaomidi** [comment]
It'd be pretty cool to see ADS on something like a chromebook or Windows 10X devices

**Pull request merged**
