### PR TITLE
Bump DacFx version to include table designer service

### PR DESCRIPTION
**Pull request by caohai**
Bump DacFx version to include table designer service

Release note for this version:
* Fixed bug when building sqlproj on Linux 
* Added Table Designer service

https://www.nuget.org/packages/Microsoft.SqlServer.DacFx/160.5332.1-preview

### CODE REVIEW

**Comment by alanrenmsft** [comment]
are we only bringing in the table designer changes?

**Comment by caohai** [comment]
> are we only bringing in the table designer changes?

I added the release note for this version to the description.

From release notes:
Fixed bug when building sqlproj on Linux 
Added Table Designer service

**Comment by alanrenmsft** [comment]
@kisantia @llali need your help to verify the dacfx related feature are working fine with the new version of dacfx package. how should we proceed here?

**Comment by kisantia** [comment]
@zijchen can you help confirm that this dacfx nuget is good to go for use here?

**Comment by alanrenmsft** [comment]
tested the table designer feature on Windows: ✔️

**Comment by caohai** [comment]
tested the table designer feature on Mac and Ubuntu ✔️

**Comment by zijchen** [comment]
> @zijchen can you help confirm that this dacfx nuget is good to go for use here?

I have already consumed this Nuget version in the SDK and all the tests passed there. https://github.com/microsoft/DacFx/pull/51

I'm unfamiliar with what we normally test for when upgrading DacFx packages here though. Shouldn't we already have coverage on DacFx functionality in the unit/integration tests?

**Comment by alanrenmsft** [comment]
> > @zijchen can you help confirm that this dacfx nuget is good to go for use here?
> 
> @kisantia @caohai I have already consumed this Nuget version in the SDK and all the tests passed there. [microsoft/DacFx#51](https://github.com/microsoft/DacFx/pull/51)
> 
> I'm unfamiliar with what we normally test for when upgrading DacFx packages here though. Shouldn't we already have coverage on DacFx functionality in the unit/integration tests?

@kisantia  is it good enough?

**Comment by kisantia** [comment]
> > > @zijchen can you help confirm that this dacfx nuget is good to go for use here?
> > 
> > 
> > @kisantia @caohai I have already consumed this Nuget version in the SDK and all the tests passed there. [microsoft/DacFx#51](https://github.com/microsoft/DacFx/pull/51)
> > I'm unfamiliar with what we normally test for when upgrading DacFx packages here though. Shouldn't we already have coverage on DacFx functionality in the unit/integration tests?
> 
> @kisantia is it good enough?

yup good with me if the only DacFx changes since the last update are fixing build on linux and the table designer changes and tests are passing. Usually we just do some basic testing of dacpac, schema compare, and projects with the new DacFx nuget, which we did for the last update. I'm not too worried about this update since this is mostly adding new stuff, not changing existing functionality.

**Review by kisantia — APPROVED** [review]

**Review by alanrenmsft — APPROVED** [review]

**Pull request merged**
