### PR TITLE
Fix batch parser test

### PR DESCRIPTION
**Pull request by abist**
Batch parser tests failing again on appveyor. Put in a pull request to run the test on appveyor.

### CODE REVIEW

**Comment by abist** [comment]
@Raymondd that's the point of this branch, no one's merging it

**Comment by Raymondd** [comment]
Yup, just making it clear so it stops being ignored. Looks like Karl didn't see it either.

**Comment by abist** [comment]
These changes now pass these tests in AppVeyor during Coveralls as well.

**Comment by kevcunnane** [comment]
:shipit:

**Pull request merged**
