### PR TITLE
Update SQL Assessment Nuget to 1.0.20230316.49 version

### PR DESCRIPTION
**Pull request by suah0205**
Update SQL Assessment nuget to 1.0.20230316.49 version which has Min Privilege Permission fix.

### CODE REVIEW

**Comment by suah0205** [comment]
Tagging @raymondtruong @austincraigbryan for FYI

**Comment by raymondtruong** [comment]
FYI @brian-harris, Sourabh has introduced this change to bump the assessment NuGet for the next release, this addresses an issue regarding minimum permissions for running assessment which we got an IcM for recently. I would need to double check what other changes this new version of the package might include, but heads up this is one extra sign off we might want to do for next release.

**Review by raymondtruong — APPROVED** [review]

**Review by brian-harris — APPROVED** [review]

**Review by austincraigbryan — APPROVED** [review]

**Comment by raymondtruong** [comment]
+ @siyao-Siyang FYI

**Review by brian-harris — APPROVED** [review]

**Comment by Charles-Gagnon** [comment]
Bulk closing stale PRs, please update and reopen if you plan on continuing this work!

**Pull request closed without merging**
