### PR TITLE
Adding decimal values to costs

### PR DESCRIPTION
**Pull request by aasimkhan30**
This PR fixes https://github.com/microsoft/azuredatastudio/issues/18884

For graphs with more than 20 nodes:
After:
image
Before:
image

For graphs with less than 20 nodes: 
image

### CODE REVIEW

**Review by kburtram — APPROVED** [review]
LGTM.  Is this the same precision that is used in SSMS?  Seems like a lot of decimal points to me, but if that is what users expects then is fine to me.

SSMS completely round up the digits so there is no decimal points. I will add Erin to this PR to get her feedback on it.

**Comment by aasimkhan30** [comment]
SSMS completely round up the digits so there is no decimal points. I will add Erin to this PR to get her feedback on it.

**Comment by erinstellato-ms** [comment]
@aasimkhan30 I reached out to the original requester, and a few other people, to get feedback on the number of decimal points.  First question would be whether it can be conditional.  In certain scenarios, show the whole numbers as we do now.  In other cases, go to decimals, with a max of either two (2) or three (3).

If you can make it conditional, I can provide suggestions for how to handle that.  It could either be based on number of operators, or number of operators and percentage numbers.

**Comment by aasimkhan30** [comment]
@erinstellato-ms, updated screenshots. For now, graphs with less than 20 nodes will have rounded up relative costs whereas graphs with more than 20 nodes will have decimal relative costs.

**Review by erinstellato-ms — COMMENTED** [review]
I think that this is a good operator count to start with for a threshold.  I assume that increasing it (if we get feedback that 20 is too low) is s somewhat simple (?) code change.

**Review by kburtram — APPROVED** [review]

**Pull request merged**
