### PR TITLE
DRAFT - Azure monitor extension

### PR DESCRIPTION
**Pull request by JustinMDotNet**

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
Does this need to be in this repo? It would be nice to have external components in their own repos instead of just continuing to put them in here. Much less risk of different projects breaking other projects in the repo (especially when using lots of shared Nuget packages).

**Comment by Charles-Gagnon** [comment]
And if this is a draft you can just use the Draft PR functionality as well so it doesn't show up as an actual PR until it's ready to review.

**Comment by JustinMDotNet** [comment]
Closing to reopen as draft.

**Comment by Charles-Gagnon** [comment]
FYI you can convert an existing PR to a draft (and vice versa)

image

**Pull request closed without merging**
