### PR TITLE
version bump

### PR DESCRIPTION
**Pull request by alanrenmsft**

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
Are you going to fix it so that we aren't changing the revision # each time? I would have expected this first one to be `4.0.1-release.0`, the second one to be `4.0.2-release.0` etc. And then hotfixes would be `4.0.1-release.1` and so on. 

(although honestly I think we should consider removing the "release" and just go with `4.0.1.0` too...)

**Comment by alanrenmsft** [comment]
I meant to create a draft pr while I test things out and I am going to email the team and collect feedback.

**Comment by alanrenmsft** [comment]
as we chatted offline, things look good after the vbump.

**Comment by Charles-Gagnon** [comment]
So the process is that we're going to manually update the version in this file to `4.1.0.0` after the next release? And then the version is always to be incrementing the revision version by 1 (so `4.0.0.0` -> `4.0.0.1` -> `4.0.0.2` and so on)?

Can we have this just be 3 numbers to match the actual semver spec? So `4.0.0`

**Comment by alanrenmsft** [comment]
the third is patch number, we use it for hot fix, and the fourth number is build number, incremented automatically by the build script.

**Comment by Charles-Gagnon** [comment]
Right, ok yeah that makes sense.

**Review by Charles-Gagnon — APPROVED** [review]

**Pull request merged**
