### PR TITLE
bump migration assessment nuget

### PR DESCRIPTION
**Pull request by cssuh**
This will allow me to get the latest changes for the migration assessment api

### CODE REVIEW

**Review by aasimkhan30 — APPROVED** [review]

**Review by aasimkhan30 — CHANGES_REQUESTED** [review]
Pipeline agents are not able to find this package in the mssqltools feed. You will probably have to add a reference from msdata to mssqltools for this version.

**Comment by Charles-Gagnon** [comment]
Where is this package coming from? As Aasim pointed out you haven't pushed it to the mssqltools feed so the builds will fail until that happens.

But also we can't have packages in that feed anyways since this is an open source project. Can you ask the Migration team if they can get this package published on Nuget.org? Because otherwise we'll need to go back to just checking in the package directly in the repo which isn't great.

**Comment by Charles-Gagnon** [comment]
I'm also curious how you even built this with the package missing from the feed. You should always be building and testing locally before updating dependencies - did you have the package in your local nuget cache or something already?

**Comment by cssuh** [comment]
Yep my mistake, I thought I could just bump the version.

**Pull request closed without merging**
