### PR TITLE
Fixing sqlcore nuget dlls not being signed.

### PR DESCRIPTION
**Pull request by aasimkhan30**
The fix was to reorder the steps in pipeline so that we are packing sqlcore just after signing it. 

https://github.com/microsoft/sqltoolsservice/blob/1eba98384a4100151160d68ac4b1a4f39338dce1/azure-pipelines/build.yml#L286
This step was rebuilding some of the projects in the directory thereby overwriting the files we signed in the esrp step for sqlcore. By packaging sqlcore before the rebuild, we are making sure we get the signed files.

### CODE REVIEW

**Review by Charles-Gagnon — APPROVED** [review]
@corivera I noticed that the Tools binaries aren't being signed either. Do you have time to look into fixing that?

**Review by Charles-Gagnon — APPROVED** [review]

**Comment by corivera** [comment]
@Charles-Gagnon Sure

**Comment by corivera** [comment]
Although I remember doing certificate checks before uploading them to nuget. Is this a recent bug?

**Comment by corivera** [comment]
Maybe that was just the package itself getting signed

**Pull request merged**
