### PR TITLE
Multi-targeting SqlCore

### PR DESCRIPTION
**Pull request by Benjin**
Adding back netstandard2.0 until that dependency can be dropped, and adding conditionals for QueryStore package reference and consumption

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
Please:

1. Make an issue (preferably with the other workload items) to track removing this once we've moved over to the SqlToolsCore workload
2. Add comment(s) linking to that work item - at least one wherever you IFDEF stuff out

**Review by aasimkhan30 — APPROVED** [review]

**Comment by Benjin** [comment]
@Charles-Gagnon

> Please:
> 
> 1. Make an issue (preferably with the other workload items) to track removing this once we've moved over to the SqlToolsCore workload
> 2. Add comment(s) linking to that work item - at least one wherever you IFDEF stuff out

Done, tracking removal in SqlToolsCore as Task #1254787

**Review by Charles-Gagnon — APPROVED** [review]

**Comment by Charles-Gagnon** [comment]
Can you make sure the test failures aren't related to this change?

**Comment by Benjin** [comment]
@Charles-Gagnon 

> Can you make sure the test failures aren't related to this change?

Everything's passing locally except for the test that requires a storage account to be set up, which is failing because I don't have those reg keys populated, so it looks good.

**Pull request merged**
