### PR TITLE
Always sign artifacts

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Previously signing was controlled by the `signed` var for binaries. To avoid the possibility of releasing unsigned bits I'm changing it to just always sign even things, even if we aren't releasing it.

### CODE REVIEW

**Review by kburtram — APPROVED** [review]
Is signing causing some type of problem?  Do we force this variable to true when the release flag is true?  Otherwise, I'm concerned we may end up shipping unsigned bits at some point.

**Comment by Charles-Gagnon** [comment]
Not specifically, but the signing of the binaries was controlled by the signing var so this is more about being consistent.

But your suggestion of forcing signed to true when release is true is a good one. I'll do that as well.

**Comment by kburtram** [comment]
Thanks, that makes sense.  If we can ensure all the packages we push to github are signed I think we're good.  Otherwise, the risk of shipping unsigned bits at some point in the future seems unnecessarily high (...and we should likely just sign everything, in that case).

**Review by alanrenmsft — APPROVED** [review]

**Comment by Charles-Gagnon** [comment]
Alright, updated it to just always sign things regardless

**Review by alanrenmsft — APPROVED** [review]

**Pull request merged**
